"""The omnibox filter grammar and its translation to SQL.

One grammar, parsed in one place, because the filter state used to be spread
over a search field, three combo boxes and two checkboxes -- six widgets that
each owned a fragment of the WHERE clause and had to be kept mutually
consistent by hand. Everything that narrows the asset table is now a token in
a single string: `prefix:value` chips for the grouping levels, `is:` flags,
`val:` comparisons, and bare words. That makes the whole filter state
trivially serialisable (saved views store `to_text()` output), and it gives
every other control a single verb -- rail rows, value-map segments and
context-menu items all "add a chip" instead of each poking a different widget.

Bare text deliberately matches only the item name and the custom name, unlike
the old search field which also swept location, system, region, owner, group
and category. Typing "jita" there matched every single asset docked in Jita,
which made free text useless for finding an item at a busy hub -- the one
thing free text is actually for. Anyone who wants to filter on a place or an
owner has a chip for it, and the completer offers them; the bare words are
reserved for "find my thing called this".

Everything here is Qt-free on purpose: the grammar is exercised by plain
pytest without a window, and the SQL it produces is written against the inner
aliases of `queries.ASSET_ROWS` (t, a, p, mg, ...) so it composes with the
same subquery-injection idiom the rest of `queries.py` uses.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from . import queries
from .config import ASSET_SAFETY_LOCATION_ID

# The chip kinds that filter one grouping level by exact label. Six of them
# come from queries.ROLLUP_LEVELS; meta is extra -- it is not a rail grouping level,
# but "show me only Tech II" is too useful to leave out of the grammar.
LEVEL_KINDS = ("location", "system", "region", "owner", "category", "group", "meta")

IS_FLAGS = ("fitted", "safety", "unpriced", "bpc")

# Short forms are what people type; the long forms are accepted too so that
# to_text() output and hand-written saved views both parse regardless of which
# spelling they used.
_PREFIX_TO_KIND = {
    "loc": "location",
    "location": "location",
    "sys": "system",
    "system": "system",
    "region": "region",
    "owner": "owner",
    "cat": "category",
    "category": "category",
    "group": "group",
    "meta": "meta",
    # item: is the exact-name axis "Where else is this?" filters on. Bare
    # text cannot serve that gesture -- LIKE %Tritanium% also counts every
    # Compressed Tritanium stack, which inflates the answer for any item
    # whose name is a substring of another's.
    "item": "item",
}
_KIND_TO_PREFIX = {"location": "loc", "system": "sys", "category": "cat"}

# val: comparisons -- an operator, a number, and an optional ISK magnitude
# suffix (k/m/b/t), e.g. val:>10m. Anchored on both ends so trailing garbage
# falls through to bare text instead of silently parsing as a comparison.
_VAL_RE = re.compile(r"^(>=|<=|>|<)(\d+(?:\.\d+)?)([kmbt]?)$", re.IGNORECASE)
_VAL_SUFFIX = {"": 1, "k": 1e3, "m": 1e6, "b": 1e9, "t": 1e12}

# is:fitted is the same "does my direct parent belong to the Ship category"
# question the hide-ship-contents checkbox asked, with the polarity flipped:
# the clause in queries.py keeps loose items, this variant keeps the fitted
# and carried ones. Derived from the same string so the two can never drift.
_FITTED_EXISTS = queries.HIDE_SHIP_CONTENTS_CLAUSE.replace("NOT EXISTS", "EXISTS", 1)

# Positive and negated SQL per is: flag. Each pair is written out rather than
# generated by wrapping NOT(...) because the naive negation is wrong for some
# of them: NULL root_location_id rows must survive -is:safety, and the
# fitted pair already exists in both polarities.
_IS_SQL = {
    "fitted": (_FITTED_EXISTS, queries.HIDE_SHIP_CONTENTS_CLAUSE),
    "safety": (
        f"a.root_location_id = {ASSET_SAFETY_LOCATION_ID}",
        f"a.root_location_id IS NOT {ASSET_SAFETY_LOCATION_ID}",
    ),
    "unpriced": (
        "COALESCE(p.source, 'none') = 'none'",
        "COALESCE(p.source, 'none') <> 'none'",
    ),
    "bpc": ("a.is_blueprint_copy = 1", "a.is_blueprint_copy = 0"),
}


@dataclass
class Chip:
    """One parsed token: a level filter, an is: flag, or a val: comparison."""

    kind: str  # one of LEVEL_KINDS, or "is", or "val"
    value: str
    negated: bool = False


@dataclass
class FilterSpec:
    """The full filter state: bare search words plus the chips."""

    text: str = ""
    chips: list[Chip] = field(default_factory=list)

    @property
    def is_empty(self) -> bool:
        return not self.chips and not self.text.strip()

    def describe(self) -> int:
        """How many filters are active, for the "N filters" state row.

        All the bare words count as one filter together: they render as one
        editable string, so they clear as one.
        """
        return len(self.chips) + (1 if self.text.strip() else 0)

    def to_text(self) -> str:
        """Serialise back to grammar text that parse() reads to an equal spec.

        This is the saved-view format: one line of the same grammar the user
        types, so a saved view can be inspected, edited or shared as text
        rather than being an opaque blob. The round-trip guarantee
        parse(spec.to_text()) == spec holds for any chips whose values are
        semantically valid (is: values from IS_FLAGS, val: values matching
        the comparison grammar; level values may be any string at all) --
        property-tested in tests/test_omni.py, because the first version of
        this pair quietly corrupted saved views on three shapes of value:
        embedded quotes, embedded non-space whitespace, and empty labels.
        """
        parts = []
        for c in self.chips:
            prefix = _KIND_TO_PREFIX.get(c.kind, c.kind)
            parts.append(("-" if c.negated else "") + f"{prefix}:{_quote_value(c.value)}")
        for word in self.text.split():
            # A bare word that would re-tokenise as a chip (someone searched
            # the literal text "cat:mystery"), or that carries a quote, gets
            # wrapped -- parse() unquotes a quoted bare token back to text,
            # so the word survives recall instead of quietly becoming a
            # different filter than the one that was saved.
            if '"' in word or parse(word).chips:
                escaped = word.replace("\\", "\\\\").replace('"', '\\"')
                word = f'"{escaped}"'
            parts.append(word)
        return " ".join(parts)

    def where(self, exclude_level: str | None = None) -> tuple[str, tuple]:
        """SQL WHERE (no leading keyword) against ASSET_ROWS' inner aliases.

        Composition rules: every bare word must match (AND); positive chips
        of the same kind OR together (picking two locations means "either");
        different kinds, negations, flags and comparisons all AND. Values
        travel as bound parameters -- the only strings interpolated into the
        SQL are expressions this module owns.

        exclude_level drops chips of that kind, both polarities. The rail
        facets its rows by every filter except its own level, so that picking
        one location still shows the other locations to switch to.
        """
        clauses: list[str] = []
        params: list = []

        for word in self.text.split():
            clauses.append("(t.name LIKE ? OR a.custom_name LIKE ?)")
            params.extend([f"%{word}%"] * 2)

        chips = [c for c in self.chips if c.kind != exclude_level]

        for kind in (*LEVEL_KINDS, "item"):
            # item is not a grouping level, but it filters exactly like one:
            # an exact match on a single expression, OR-able and negatable.
            # The .get default serves meta, the one LEVEL_KINDS entry with no
            # rail level behind it (see the LEVEL_KINDS comment above).
            expr = "t.name" if kind == "item" else queries.OVERVIEW_FILTER_EXPR.get(kind, "mg.name")
            positive = [c for c in chips if c.kind == kind and not c.negated]
            if positive:
                clauses.append("(" + " OR ".join([f"{expr} = ?"] * len(positive)) + ")")
                params.extend(c.value for c in positive)
            for c in chips:
                if c.kind == kind and c.negated:
                    # Keep NULL-labelled rows: excluding "Tech II" must not
                    # also hide every item that has no meta group at all.
                    clauses.append(f"({expr} IS NULL OR {expr} <> ?)")
                    params.append(c.value)

        # A chip that cannot be translated is skipped, mirroring parse()'s
        # forgiveness, because chips do not only come from parse: saved views
        # written by a newer build may carry a flag this build has never
        # heard of, and applying the view's other filters beats blowing up
        # the whole assets tab over the one it cannot honour.
        for c in chips:
            if c.kind == "is":
                sql_pair = _IS_SQL.get(c.value)
                if sql_pair is None:
                    continue
                clauses.append(sql_pair[1] if c.negated else sql_pair[0])
            elif c.kind == "val":
                parsed = _parse_val(c.value)
                if parsed is None:
                    continue
                op, amount = parsed
                comparison = f"a.quantity * COALESCE(p.sell_price, 0) {op} ?"
                clauses.append(f"NOT ({comparison})" if c.negated else comparison)
                params.append(amount)

        return " AND ".join(clauses), tuple(params)


def _parse_val(value: str) -> tuple[str, float] | None:
    """The operator and the scaled amount, or None for a malformed value."""
    m = _VAL_RE.match(value)
    if m is None:
        return None
    op, number, suffix = m.groups()
    return op, float(number) * _VAL_SUFFIX[suffix.lower()]


def _tokenize(raw: str) -> list[str]:
    """Split on whitespace, except inside double quotes.

    Quotes glue rather than delimit: `loc:"Jita IV - Moon 4"` is one token
    with the quotes still attached, so the prefix split below sees them and
    _unquote can resolve just the value part. Inside a quoted region a
    backslash escapes a following quote or backslash -- to_text() emits those
    escapes for values that themselves contain a quote, and if the tokenizer
    let that escaped quote toggle the quoted state it would swallow every
    later token into one (the saved-view corruption this pair of functions is
    property-tested against). The escape pair is kept verbatim here so a
    token that falls back to bare text keeps exactly what the user typed.
    """
    tokens: list[str] = []
    buf: list[str] = []
    quoted = False
    i = 0
    while i < len(raw):
        ch = raw[i]
        if quoted and ch == "\\" and i + 1 < len(raw) and raw[i + 1] in '"\\':
            buf.append(ch)
            buf.append(raw[i + 1])
            i += 2
            continue
        if ch == '"':
            quoted = not quoted
            buf.append(ch)
        elif ch.isspace() and not quoted:
            if buf:
                tokens.append("".join(buf))
                buf = []
        else:
            buf.append(ch)
        i += 1
    if buf:
        tokens.append("".join(buf))
    return tokens


def _unquote(value: str) -> str:
    """Resolve quoting and escapes in a chip value: the inverse of _quote_value.

    Unescaped quotes delimit and are dropped; inside them, backslash-escaped
    quotes and backslashes become literal. Outside a quoted region a
    backslash is an ordinary character -- station names do not contain them,
    but a half-typed Windows-path-looking search must not eat its own
    separators.
    """
    out: list[str] = []
    quoted = False
    i = 0
    while i < len(value):
        ch = value[i]
        if quoted and ch == "\\" and i + 1 < len(value) and value[i + 1] in '"\\':
            out.append(value[i + 1])
            i += 2
            continue
        if ch == '"':
            quoted = not quoted
        else:
            out.append(ch)
        i += 1
    return "".join(out)


def _quote_value(value: str) -> str:
    """Serialise one chip value so parse() reads it back verbatim.

    Quoting triggers on any whitespace (the tokenizer splits on isspace, not
    just on spaces), on an embedded quote (which must also be escaped, or it
    would toggle the tokenizer's quoted state mid-value), and on the empty
    string (an unquoted `loc:` is the half-typed-token shape parse treats as
    bare text). Backslashes are escaped first so the quote escapes survive.
    """
    if value and '"' not in value and not any(ch.isspace() for ch in value):
        return value
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def parse(raw: str) -> FilterSpec:
    """Parse omnibox text into a FilterSpec.

    Forgiving by design: anything that does not parse as a chip -- an unknown
    prefix, an is: flag this app has never heard of, a malformed val:
    comparison -- degrades to a bare search word rather than raising. The
    omnibox re-parses on every keystroke, so half-typed tokens are the normal
    case, not an error.
    """
    words: list[str] = []
    chips: list[Chip] = []
    for token in _tokenize(raw or ""):
        body = token
        negated = False
        if body.startswith("-") and len(body) > 1:
            negated = True
            body = body[1:]

        prefix, sep, raw_value = body.partition(":")
        value = _unquote(raw_value)
        chip = None
        # A quoted empty value (`loc:""`) is a deliberate empty-label filter
        # and to_text() serialises empty-value chips exactly that way, so the
        # two halves agree; an unquoted empty value (`loc:`) is the normal
        # half-typed state and stays bare text.
        if sep and (value or '"' in raw_value):
            kind = _PREFIX_TO_KIND.get(prefix.lower())
            if kind is not None:
                chip = Chip(kind=kind, value=value, negated=negated)
            elif prefix.lower() == "is" and value.lower() in IS_FLAGS:
                chip = Chip(kind="is", value=value.lower(), negated=negated)
            elif prefix.lower() == "val" and _VAL_RE.match(value):
                chip = Chip(kind="val", value=value, negated=negated)
        if chip is not None:
            chips.append(chip)
        elif token.startswith('"'):
            # A quoted bare token is the escape hatch for text that would
            # otherwise read as a token; to_text() wraps such words, so the
            # quotes come off here to complete the round trip.
            words.append(_unquote(token))
        else:
            words.append(token)
    return FilterSpec(text=" ".join(words), chips=chips)
