#!/usr/bin/env python3
"""Stamp src/evasset/_version.py from the git tag being released.

    python scripts/set_version.py v1.2.3

Run by .github/workflows/release.yml before Nuitka compiles, so the version
the app reports, the version in the Windows exe resource and the tag on the
commit are the same string by construction. Nothing is bumped by hand, and
there is no second constant to forget.

Two different forms come out of one tag, because Windows and humans disagree
about what a version is:

  tag            __version__     Windows file version
  v1.2.3         1.2.3           1.2.3.0
  v1.2.3.4       1.2.3.4         1.2.3.4
  v1.2.3-rc1     1.2.3-rc1       1.2.3.0

A Windows VERSIONINFO resource is four 16-bit integers and cannot hold "rc1",
so the numeric core is used there while the full tag stays in __version__.
That is what makes a release candidate taggable at all: it builds and
publishes with an honest -rc1 in the About box, and release.yml marks it a
GitHub prerelease so the in-app updater -- which reads /releases/latest, and
that endpoint skips prereleases -- never offers it to anyone.

A tag that is not a version is a hard error rather than a silent fallback to
0.0.0. A build stamped 0.0.0 would look older than every real release to
updater.parse_version, so every user would be offered a "newer" build forever;
failing the release is the cheaper mistake.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_FILE = ROOT / "src" / "evasset" / "_version.py"

# v1.2.3 / 1.2.3.4 / v1.2.3-rc1 -- 2 to 4 numeric parts, optional suffix.
TAG_RE = re.compile(r"^v?(?P<core>\d+(?:\.\d+){1,3})(?P<suffix>[-+].+)?$")


def parse_tag(tag: str) -> tuple[str, str]:
    """("v1.2.3-rc1") -> ("1.2.3-rc1", "1.2.3.0").

    Returns the version to report and the four-part numeric one Windows wants.
    Raises ValueError on anything that is not a version tag.
    """
    match = TAG_RE.match((tag or "").strip())
    if match is None:
        raise ValueError(
            f"{tag!r} is not a version tag. Expected vMAJOR.MINOR[.PATCH[.BUILD]] "
            "with an optional -suffix, for example v1.2.3 or v1.2.3-rc1."
        )
    core = match.group("core")
    version = core + (match.group("suffix") or "")
    # Pad to the four parts a VERSIONINFO resource is made of.
    parts = core.split(".")
    file_version = ".".join(parts + ["0"] * (4 - len(parts)))
    return version, file_version


def render(version: str) -> str:
    """The whole file, not a line patched in place -- a regex substitution
    that silently matched nothing is exactly the failure this script exists to
    prevent."""
    return (
        '"""Generated by scripts/set_version.py from the release tag. Do not edit.\n'
        "\n"
        "The committed copy of this file carries a .dev version; this one was\n"
        "written during a tagged build. See the script for why the tag is the\n"
        'only source of truth.\n'
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        f'__version__ = "{version}"\n'
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("tag", help="the git tag being released, e.g. v1.2.3")
    parser.add_argument(
        "--check",
        action="store_true",
        help="parse and report only; do not write _version.py",
    )
    args = parser.parse_args()

    try:
        version, file_version = parse_tag(args.tag)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if not args.check:
        VERSION_FILE.write_text(render(version), encoding="utf-8")
        print(f"wrote {VERSION_FILE.relative_to(ROOT)}: __version__ = {version!r}")

    # Hand both forms back to the workflow so the Nuitka flags and the app
    # agree without release.yml re-implementing any of this parsing.
    output = os.environ.get("GITHUB_OUTPUT")
    if output:
        with open(output, "a", encoding="utf-8") as handle:
            handle.write(f"version={version}\n")
            handle.write(f"file_version={file_version}\n")
    print(f"version={version}")
    print(f"file_version={file_version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
