; Inno Setup script for EVE Booty.
;
; Wraps the Nuitka --standalone program folder (dist\EVEBooty) into an
; installer. The portable zip is still published alongside it -- this is an
; alternative for people who want Start menu entries and an entry in Apps &
; features, not a replacement.
;
; Build it with:
;   uv run python build.py --installer            (calls ISCC if installed)
;   ISCC.exe dist_assets\win\eve-booty.iss        (manually)
;
; Install Inno Setup with:  winget install JRSoftware.InnoSetup

#define AppName    "EVE Booty"
#define AppExe     "evebooty.exe"
#define AppFolder  "EVEBooty"
; CI passes both with /DAppVersion=1.2.3 /DFileVersion=1.2.3.0
;
; Two of them because they answer to different rules. AppVersion is shown to
; the user and goes in the filename, so it matches the zip and can carry a
; "-rc1" suffix. VersionInfoVersion is a Windows version resource, which is
; four integers and rejects anything else, so it gets the numeric core.
#ifndef AppVersion
  #define AppVersion "0.0.0"
#endif
#ifndef FileVersion
  #define FileVersion "0.0.0.0"
#endif

[Setup]
; Generated for this app. Must never be shared with another product -- Inno
; treats a matching AppId as "the same application", so a duplicate would let
; one installer upgrade or uninstall the other.
AppId={{8D90DCE3-7D01-4EC1-928C-7D688C578C7B}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher=LittlePhish
AppPublisherURL=https://github.com/littlephish/eve-booty
AppSupportURL=https://github.com/littlephish/eve-booty/issues
AppUpdatesURL=https://github.com/littlephish/eve-booty/releases
VersionInfoVersion={#FileVersion}
DefaultDirName={autopf}\{#AppFolder}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes

; Per-user by default, and this one is load-bearing rather than a courtesy.
; With PrivilegesRequired=lowest, {autopf} resolves to
; %LOCALAPPDATA%\Programs, which the user can write to -- so
; updater.can_write_install_dir() is true and Help -> Check for updates keeps
; working. Installed into Program Files instead, the in-app updater would
; correctly disable itself and every update would have to be done by hand.
; It also avoids a UAC prompt, which is one less thing for endpoint protection
; to take an interest in.
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

OutputDir=..\..\dist
OutputBaseFilename={#AppFolder}-{#AppVersion}-setup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
; Generated by scripts/make_icon.py, which the release workflow runs before
; this script is compiled.
SetupIconFile=..\..\src\evasset\assets\booty.ico
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible
UninstallDisplayName={#AppName}
UninstallDisplayIcon={app}\{#AppExe}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Files]
; The whole Nuitka standalone folder, update.exe included -- the in-app
; updater copies that one file out to temp and runs it from there to replace
; the install, so it has to ship inside the folder.
Source: "..\..\dist\{#AppFolder}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExe}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#AppExe}"; Description: "Launch {#AppName}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Left behind by an in-app update rather than installed by this script, so the
; uninstaller does not know about them: the helper's log, and the staging
; folder if an update was interrupted part way through.
Type: files; Name: "{app}\update-log.txt"
Type: filesandordirs; Name: "{app}\update"
; Assets, wallet history, settings and the SDE live in %APPDATA%\eve-booty and
; are deliberately kept. Reinstalling keeps every character and the wallet
; journal, which holds history ESI will no longer serve. Deleting that folder
; is the user's call to make, not the uninstaller's.
Type: dirifempty; Name: "{app}"
